// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN-6t0DgppGZa5kw8Aase6AE_FJWp3wzs',
    appId: '1:7964827841:web:b9c88abfce9df9a15d3440',
    messagingSenderId: '7964827841',
    projectId: 'payezy-project',
    authDomain: 'payezy-project.firebaseapp.com',
    storageBucket: 'payezy-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzsWf6Ta3JPsMp4VHe_FU1IhR2b5C_TUQ',
    appId: '1:7964827841:android:26f567239e1e01125d3440',
    messagingSenderId: '7964827841',
    projectId: 'payezy-project',
    storageBucket: 'payezy-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVnShJ2UhJutikYjvVa9JMypT6UUhAL-M',
    appId: '1:7964827841:ios:2a797290b42ff8935d3440',
    messagingSenderId: '7964827841',
    projectId: 'payezy-project',
    storageBucket: 'payezy-project.appspot.com',
    iosBundleId: 'com.example.payezy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVnShJ2UhJutikYjvVa9JMypT6UUhAL-M',
    appId: '1:7964827841:ios:fa1c6ffc83d05cc15d3440',
    messagingSenderId: '7964827841',
    projectId: 'payezy-project',
    storageBucket: 'payezy-project.appspot.com',
    iosBundleId: 'com.example.payezy.RunnerTests',
  );
}
